apiVersion: v1 
kind: Service 
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
  - targetPort: {{ .Values.databaseport.port.containerPort}}
    port: {{ .Values.databaseport.port.containerPort}}