backend:
  image:
    registry: docker.io
    repository: kanchannath/eks-backend
    tag: "4.1-89dd6e6"
    digest: ""
    pullPolicy: IfNotPresent
database:
  image:
    registry: docker.io
    repository: library/mysql
    tag: "8.0"
    digest: ""
    pullPolicy: IfNotPresent
backendport:
  port:
    containerPort: 8080
databaseport:
  port:
    containerPort: 3306
